version: "3.9"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lab1
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
  application:
    image: baliharko/bank_lab:latest
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
      RISK_URL: http://risk:8080
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  risk:
    image: daneidmark/risk:0.0.1
    ports:
      - "8082:8080"
